"""Deep end-to-end prediction pipeline interface."""

from .contracts import (
    ArtifactProvenance,
    AttentionInspection,
    CaseInput,
    ClassificationPrediction,
    ClassifierAdapterTimings,
    ClassifierInputSummary,
    ClassifierStageTimings,
    Detection,
    DetectorAdapterTimings,
    DetectorInputSummary,
    DetectorPrediction,
    DetectorStageTimings,
    GeometrySummary,
    InputSummary,
    MemorySummary,
    NumericTensor,
    PredictionMode,
    PredictionProvenance,
    PredictionResult,
    PredictionTimings,
    PredictionWarning,
    RuntimeExecutionSummary,
    TokenizerProvenance,
)
from .pipeline import (
    PredictionContractError,
    PredictionInputError,
    PredictionPipeline,
    PredictionPipelineError,
)
from .serialization import prediction_from_dict, prediction_to_dict

__all__ = [
    "ArtifactProvenance",
    "AttentionInspection",
    "CaseInput",
    "ClassificationPrediction",
    "ClassifierAdapterTimings",
    "ClassifierInputSummary",
    "ClassifierStageTimings",
    "Detection",
    "DetectorAdapterTimings",
    "DetectorInputSummary",
    "DetectorPrediction",
    "DetectorStageTimings",
    "GeometrySummary",
    "InputSummary",
    "MemorySummary",
    "NumericTensor",
    "PredictionContractError",
    "PredictionInputError",
    "PredictionMode",
    "PredictionPipeline",
    "PredictionPipelineError",
    "PredictionProvenance",
    "PredictionResult",
    "PredictionTimings",
    "PredictionWarning",
    "RuntimeExecutionSummary",
    "TokenizerProvenance",
    "prediction_to_dict",
    "prediction_from_dict",
]
