"""Single-residency accelerator runtime interface."""

from .runtime import (
    AcceleratorLifecycle,
    ExecutionTimings,
    LifecycleMetrics,
    LifecycleTimings,
    MemorySnapshot,
    ModelBinding,
    ModelOutputs,
    PersistentResidencyRuntime,
    ResidencyRuntimeError,
    ResidentModel,
    RuntimeArtifactIdentity,
    RuntimeFailure,
    RuntimeInferenceError,
    RuntimeLoadError,
    RuntimeState,
    RuntimeStatus,
    RuntimeUnavailableError,
    RuntimeUnloadError,
    SingleResidencyRuntime,
    TorchCudaLifecycle,
    UnknownModelError,
)

__all__ = [
    "AcceleratorLifecycle",
    "ExecutionTimings",
    "LifecycleMetrics",
    "LifecycleTimings",
    "MemorySnapshot",
    "ModelBinding",
    "ModelOutputs",
    "PersistentResidencyRuntime",
    "ResidencyRuntimeError",
    "ResidentModel",
    "RuntimeArtifactIdentity",
    "RuntimeFailure",
    "RuntimeInferenceError",
    "RuntimeLoadError",
    "RuntimeState",
    "RuntimeStatus",
    "RuntimeUnavailableError",
    "RuntimeUnloadError",
    "SingleResidencyRuntime",
    "TorchCudaLifecycle",
    "UnknownModelError",
]
